### PR TITLE
Remove .gitignore files.

### PR DESCRIPTION
**Pull request by juanfra684**

### CODE REVIEW

**Comment by yasuoka** [comment]
@juanfra684 can you provide the reason why it should be ignored?

**Comment by juanfra684** [comment]
Someone could commit a gitignore file to a CVS repo which could hide local changes for the users of the git repo. I think that is similar to the problem with the .git directories in CVS repos. Also, I saw a few gitignore files committed to the OpenBSD src repo.

Would you willing to accept similar changes to ignore mercurial files (e.g. .hg, .hgtags, etc) in the git repo?. I would like to use your python script to convert CVS -> Git -> Mercurial and those directories could generate conflicts if someone commits local mercurial files by error to the CVS repo.

**Comment by yasuoka** [comment]
> Someone could commit a gitignore file to a CVS repo which could hide local changes for the users of the git repo. I think that is similar to the problem with the .git directories in CVS repos. Also, I saw a few gitignore files committed to the OpenBSD src repo.

Having ".git" seems a serious problem for git.

https://github.com/git/git/blob/v2.20.1/read-cache.c#L907-#L989

git(1) refuses adding it.  But I don't think having ".gitignore" is such the problem.

Adding ".gitignore" to CVS repo may be a problem or non-sense, but I don't think cvs2gitdump should fix that problem since the problem is a  part of the history.

> Would you willing to accept similar changes to ignore mercurial files (e.g. .hg, .hgtags, etc) in the git repo?. I would like to use your python script to convert CVS -> Git -> Mercurial and those directories could generate conflicts if someone commits local mercurial files by error to the CVS repo.

No, I don't want to filter such the changes if it doesn't cause a fatal problem for the converted repo.

**Comment by juanfra684** [comment]
OK, thanks anyway.

**Comment by yasuoka** [comment]
thank you too.

**Pull request closed without merging**
